name: xwidgets-demo
channels:
- conda-forge
dependencies:
- xeus-cpp=0.10.0
- xwidgets=0.30.0
- jupyterlab # or `notebook` (for classic jupyter notebook)
- jupyterlab_widgets=3.* # or `widgetsnbextension` with `notebook`
